### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by QwertyIsCoding** [eplasbaba-uwu/calculator-python#1]
This might be a false flag... Not sure
![image](https://user-images.githubusercontent.com/77963043/170799007-4a76b902-d30f-4264-a3b8-a4bbc4e1787f.png)
Reasons:
![image](https://user-images.githubusercontent.com/77963043/170799023-cd12d078-d3a5-48ef-a712-83d5086392ee.png)
This is based on VirusTotal upload results.

**Comment by adwaith-pn** [comment]
ok. changed the repository. i have removed the exe file. it shouldn't be a problem now.
